services:
  postgres:
    image: postgres:16-alpine
    container_name: nuvo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    command: -p 5444
    network_mode: host
    volumes:
      - ./docker/init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
